#bin/sh

. ./.env.prod

SQLFILE_PATH=mariadb/create-user.sql

echo "CREATE USER '$API_ABC_ECOMMERCE_BDD_USER'@'localhost' IDENTIFIED BY '$API_ABC_ECOMMERCE_BDD_MDP';" > $SQLFILE_PATH
echo "CREATE USER '$API_ABC_CONFIGURATOR_BDD_USER'@'localhost' IDENTIFIED BY '$API_ABC_CONFIGURATOR_BDD_MDP';" >> $SQLFILE_PATH
echo "GRANT ALL PRIVILEGES ON \`abc-ecommerce\` . * TO '$API_ABC_ECOMMERCE_BDD_USER'@'localhost';" >> $SQLFILE_PATH
echo "GRANT ALL PRIVILEGES ON \`abc-ecommerce\` . * TO '$API_ABC_CONFIGURATOR_BDD_USER'@'localhost';" >> $SQLFILE_PATH