FROM jenkins/jenkins:alpine-jdk11

USER root

RUN apk add git curl

RUN JENKINS_CRUMB=`curl "localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"`

RUN curl -X POST -H $JENKINS_CRUMB -F "jenkinsfile=<Jenkinsfile-ecb" $JENKINS_URL/pipeline-model-converter/validate