version: "3.8"

services:
    mariadb:
        image: mariadb
        restart: always
        ports:
            - "37612:3306"
        networks:
            - ecb-bdd
            - cob-bdd
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: abc-ecommerce
    ecb:
        build:
            dockerfile: Dockerfile
            context: openjdk16
        depends_on: 
            - install
        command:
            - ecb
        ports:
            - "57024:57024"
        networks:
            - ecb-bdd
            - ecommerce
        volumes:
            - v-ecb:/appli
        environment:
            - API_ABC_ECOMMERCE_BDD_URL=jdbc:mysql://mariadb:3306/abc-ecommerce
            - API_ABC_ECOMMERCE_BDD_USER=${API_ABC_ECOMMERCE_BDD_USER}
            - API_ABC_ECOMMERCE_BDD_MDP=${API_ABC_ECOMMERCE_BDD_MDP}
            - API_ABC_ECOMMERCE_JWT_SECRET=${API_ABC_ECOMMERCE_JWT_SECRET}
    ecf:
        build:
            dockerfile: Dockerfile
            context: nginx
        depends_on: 
            - ecb
        ports:
            - "19034:80"
        volumes:
            - v-ecf:/usr/share/nginx/html
    cob:
        build:
            dockerfile: Dockerfile
            context: openjdk16
        depends_on: 
            - install
        command:
            - cob
        ports:
            - "15013:15013"
        networks:
            - cob-bdd
            - configurator
        volumes:
            - v-cob:/appli
        environment:
            - API_ABC_ECOMMERCE_BDD_URL=jdbc:mysql://mariadb:3306/abc-ecommerce
            - API_ABC_CONFIGURATOR_BDD_USER=${API_ABC_ECOMMERCE_BDD_USER}
            - API_ABC_CONFIGURATOR_BDD_MDP=${API_ABC_ECOMMERCE_BDD_MDP}
            - API_ABC_ECOMMERCE_JWT_SECRET=${API_ABC_ECOMMERCE_JWT_SECRET}
    cof:
        build:
            dockerfile: Dockerfile
            context: nginx
        depends_on: 
            - cob
        ports:
            - "32829:80"
        volumes:
            - v-cof:/usr/share/nginx/html
    install:
        build:
            dockerfile: Dockerfile
            context: install
        depends_on: 
            - mariadb
        command:
            - all
        networks:
            - ecommerce
            - configurator
        volumes:
            - v-ecb:/deploy/ecb
            - v-ecf:/deploy/ecf
            - v-cob:/deploy/cob
            - v-cof:/deploy/cof
        environment:
            - API_ABC_ECOMMERCE_JWT_SECRET=${API_ABC_ECOMMERCE_JWT_SECRET}
            - VUE_APP_API_URL=http://localhost:57024/api/v1
            - VUE_APP_CONF_URL=http://localhost:32829/item
            - CONF_API_URL=http://localhost:15013/api/v1
            - VUE_APP_ECOM_URL=http://localhost:19034
    
networks:
    ecb-bdd:
    ecommerce:
    cob-bdd:
    configurator:

volumes:
    v-ecb:
    v-ecf:
    v-cob:
    v-cof: